name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run : echo "${GITHUB_WORKSPACE}"   
    
    - name: Install dependencies
      run: npm install --prefix "test_repo/tree/main/test_github"

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build
